source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'libevent_Example', :exclusive => true do
  pod "libevent", :path => "../"
end

target 'libevent_Tests', :exclusive => true do
  pod "libevent", :path => "../"

  
end
